I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 54, in script
    me "¿Qué sucede, Gou?"
IOError: Couldn't find file 'sounds/Fertilizer.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 54, in script
    me "¿Qué sucede, Gou?"
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\ast.py", line 603, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\exports.py", line 1121, in say
    who(what, interact=interact)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\character.py", line 828, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\character.py", line 690, in do_display
    **display_args)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\character.py", line 493, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\ui.py", line 277, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\display\core.py", line 2424, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\display\core.py", line 2715, in interact_core
    renpy.audio.audio.interact()
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\audio\audio.py", line 790, in interact
    periodic()
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\audio\audio.py", line 724, in periodic
    c.periodic()
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\audio\audio.py", line 340, in periodic
    topf = load(self.file_prefix + topq.filename + self.file_suffix)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\audio\audio.py", line 74, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\OhMyCaaat\Desktop\Todo\RenPy\renpy\loader.py", line 533, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'sounds/Fertilizer.mp3'.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.8.959
Los Panytas' School 0.1
